(define x1 0)
(define x2 0)
(define disc 0)
(define (sol a b c)
  (set! disc (- (* b b) (* 4 a c)))
  (if (>= disc 0)
      (set! x1 (/ (+ (- b) (sqrt disc)) (* 2 a)))
      (set! x1 (string #\N#\a#\N))
  )
  (if (>= disc 0)
      (set! x2 (/ (- (- b) (sqrt disc)) (* 2 a)))
      (set! x2 (string #\N#\a#\N))
  )  
  (list x1 x2))
