(define (lines-count addr)
  (let ((port (open-input-file addr)))
    (let loop ((lines 0) (chars 0))
      (if (eof-object? (peek-char port))
          (begin (close-input-port port)
                 (if (> chars 1)
                     (+ lines 1)
                     lines))
          (if (equal? (read-char port) #\newline)
              (if (> chars 1)
                  (loop (+ lines 1) 0)
                  (loop lines 0))
              (loop lines (+ chars 1)))))))

(lines-count "new.txt")